MainPageHeadline = "Testing 360°"
ContactHeadline = "Spojte se s námi"
OrthogonalCoveringArrays = "Orthogonal Arrays"
Pairwise = "Pairwise"
DecisionTable = "Decision Table"
DalsiTechniky = "Další techniky"
ClassificationTreeHeadline = "Classification Tree"
TestingName = 'John Doe'
TestEmail = 'john@doe.com'
TestMessage = 'This is my question.'
InvalidEmail = 'abc123'
